project:
  type: website

website:
  title: "Nick Dunagan"
  site-url: "https://nick.dunagan.org"
  favicon: "images/favicon-512.png"
  open-graph: true
  image: "images/headshot.png"

  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV

  page-footer:
    left: "Nick Dunagan"
    right: "Ph.D. Candidate in Economics, Clemson University"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: true

editor: source